<?php

function block_ie6_init() {
  
  $browser = $_SERVER['HTTP_USER_AGENT'];
  $pattern = '#MSIE [4|5|6]{1}\.\d{1}#ims';
  if (!preg_match($pattern, $browser)) { return; }
  
$html = <<<HTML

<html>
<head><title>Ancient Browser Detected</title></head>
<body>

<style>

body {
  background-color: black;
  color: white;
  width: 100%; height: 100%;
}

html {
  height: 100%;
}

#message {
  margin-top: 50px;
}

#message {
  margin-left: auto;
  margin-right: auto;
  padding: 10px;
  width: 590px;
  background-color: gray;
  border: 1px solid silver;
  text-align: justify;
  
  font-family: Zuzumbo, "Arial Unicode MS", Sylfaen;
  font-size: 12px;
  color: white;
}

#message a, #message_geo a {
  font-family: Zuzumbo, "Arial Unicode MS", Sylfaen;
  font-size: 12px;
  color: white;
}
</style>

<div align="center">
  <div id="message">
  It seems you are using an archaic version of Internet Explorer that industry
  is increasingly stopping to support. Tattler does not support this version
  of th browser.
  
  <p>Please download:
  <ul>
    <li><a href="http://www.apple.com/safari/download/">Apple Safari</a></li>
    <li><a href="http://www.google.com/chrome">Google's Chrome</a></li>
    <li><a href="http://firefox.com">Mozzila Firefox</a></li>
    <li>or newer <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx">Internet Explorer</a></li>
  </ul>
  
  We apologize for the inconvenience.
  </div>

</div>


</body>
</html>

HTML;
  
  
  echo $html;
  exit(0);
}
